export { default as HomePage } from './home';
export { default as CartPage } from './cart';
export { default as NotFoundPage } from './404'
export { default as LoginPage } from "./login"
export { default as ItemDetails } from "./item"
export { default as Checkout } from "./checkout"
export { default as User } from "./user"
export { default as WishList } from "./wishlist"
export { default as ExamplePage } from "./example"